stages:
  - test
  - build

variables:
  BUN_VERSION: "latest"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""  # Disable TLS
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_HOST_OVERRIDE: "docker"
  TESTCONTAINERS_REUSE_ENABLE: "true"

# Common template for Bun configuration
.bun-setup:
  image: oven/bun:${BUN_VERSION}
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .bun-install/cache

# Test job with Testcontainers
test:
  extends: .bun-setup
  stage: test
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false", "--privileged"]
      variables:
        DOCKER_TLS_CERTDIR: ""
  before_script:
    - apt-get update && apt-get install -y docker.io
    - bun install --frozen-lockfile
    # Check Docker connection
    - docker info || true
    # Pull Docker images in advance to speed up tests
    - docker pull postgres:latest || echo "Failed to pull postgres, continuing anyway"
    - docker pull redis:latest || echo "Failed to pull redis, continuing anyway"
  script:
    # Run linting
    - bun run lint
    # Run unit tests
    - bun test --test-file-pattern "**/*.spec.ts" --coverage
    # Run integration tests with Testcontainers
    - bun test --test-file-pattern "**/*.integration.spec.ts" --coverage || echo "Integration tests failed, but continuing"
    # Run E2E tests
    - bun test --test-file-pattern "**/*.e2e-spec.ts" --coverage || echo "E2E tests failed, but continuing"
    # Generate coverage report
    - bun run test:coverage || echo "Coverage report generation failed, but continuing"
  artifacts:
    paths:
      - coverage/
      - test-results/
    reports:
      junit: test-results/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    when: always

# Build job
build:
  extends: .bun-setup
  stage: build
  only:
    - main
    - develop
  script:
    - bun install --frozen-lockfile
    - bun run build
  artifacts:
    paths:
      - dist/ 